const smapleLead= [
  {
    "first_name": "Brittany",
    "last_name": "Glass",
    "email": "alec10@hotmail.com",
    "phone": "1221463740883",
    "company": "Larson-Williams",
    "city": "Karenburgh",
    "state": "Washington",
    "source": "facebook_ads",
    "status": "new",
    "score": 73,
    "lead_value": 33279.3,
    "last_activity_at": "2025-05-24T03:36:24",
    "is_qualified": true
  },
  {
    "first_name": "Rachel",
    "last_name": "Erickson",
    "email": "jeremy29@lopez-daniels.info",
    "phone": "9282308733044",
    "company": "Hicks-Maldonado",
    "city": "Rushview",
    "state": "Michigan",
    "source": "other",
    "status": "qualified",
    "score": 87,
    "lead_value": 17460.65,
    "last_activity_at": "2025-03-20T08:15:48",
    "is_qualified": false
  },
  {
    "first_name": "Sean",
    "last_name": "Young",
    "email": "andersonmelissa@mcknight.info",
    "phone": "0175077734723",
    "company": "Foster Group",
    "city": "Christopherberg",
    "state": "Texas",
    "source": "other",
    "status": "contacted",
    "score": 94,
    "lead_value": 45070.66,
    "last_activity_at": "2025-06-01T03:21:15",
    "is_qualified": true
  },
  {
    "first_name": "Rebecca",
    "last_name": "Diaz",
    "email": "benjaminwilliams@grimes.biz",
    "phone": "1074688655999",
    "company": "Jensen-Thompson",
    "city": "Howardborough",
    "state": "Connecticut",
    "source": "other",
    "status": "won",
    "score": 44,
    "lead_value": 43813.23,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Robert",
    "last_name": "Salinas",
    "email": "sosawilliam@thomas.org",
    "phone": "2457866544649",
    "company": "Russo LLC",
    "city": "Boydtown",
    "state": "Texas",
    "source": "events",
    "status": "lost",
    "score": 38,
    "lead_value": 49114.45,
    "last_activity_at": "2025-07-19T15:13:52",
    "is_qualified": true
  },
  {
    "first_name": "David",
    "last_name": "Banks",
    "email": "julieharvey@gmail.com",
    "phone": "8783166524487",
    "company": "Adkins, Arnold and Clark",
    "city": "Lisaburgh",
    "state": "Connecticut",
    "source": "website",
    "status": "qualified",
    "score": 23,
    "lead_value": 35486.23,
    "last_activity_at": "2025-05-13T22:23:51",
    "is_qualified": true
  },
  {
    "first_name": "Lisa",
    "last_name": "Hernandez",
    "email": "mollyruiz@harrington.com",
    "phone": "2088763134755",
    "company": "Cisneros and Sons",
    "city": "South Jacobstad",
    "state": "Georgia",
    "source": "google_ads",
    "status": "lost",
    "score": 92,
    "lead_value": 17452.91,
    "last_activity_at": "2025-07-25T15:31:43",
    "is_qualified": true
  },
  {
    "first_name": "Robert",
    "last_name": "Morris",
    "email": "flopez@williams-morris.info",
    "phone": "8335893547461",
    "company": "Olson, Joseph and Wright",
    "city": "Lake Jonathan",
    "state": "Vermont",
    "source": "referral",
    "status": "lost",
    "score": 88,
    "lead_value": 21483.66,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Kimberly",
    "last_name": "Ayala",
    "email": "matthewsingleton@gmail.com",
    "phone": "2941109992471",
    "company": "Ross-Wood",
    "city": "Port Maryfort",
    "state": "Kentucky",
    "source": "website",
    "status": "qualified",
    "score": 51,
    "lead_value": 30461.0,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Billy",
    "last_name": "Daniels",
    "email": "karen81@hotmail.com",
    "phone": "3278675457501",
    "company": "Gregory, Frey and Collins",
    "city": "Port Madeline",
    "state": "Arkansas",
    "source": "google_ads",
    "status": "won",
    "score": 45,
    "lead_value": 28857.29,
    "last_activity_at": "2025-04-02T15:15:43",
    "is_qualified": true
  },
  {
    "first_name": "Matthew",
    "last_name": "Dominguez",
    "email": "bsullivan@jacobs-summers.com",
    "phone": "2205567029258",
    "company": "Dixon-Lutz",
    "city": "North Richardport",
    "state": "Rhode Island",
    "source": "referral",
    "status": "qualified",
    "score": 31,
    "lead_value": 24133.41,
    "last_activity_at": "2025-05-02T10:20:26",
    "is_qualified": false
  },
  {
    "first_name": "Jamie",
    "last_name": "Chavez",
    "email": "terrihoward@yahoo.com",
    "phone": "7772299075636",
    "company": "Webster-Lee",
    "city": "West Joyce",
    "state": "Iowa",
    "source": "events",
    "status": "new",
    "score": 44,
    "lead_value": 41093.7,
    "last_activity_at": "2025-04-03T15:58:13",
    "is_qualified": false
  },
  {
    "first_name": "Erica",
    "last_name": "Williams",
    "email": "lambertvalerie@yahoo.com",
    "phone": "2415700230682",
    "company": "Thomas, Norris and Cooley",
    "city": "Amberhaven",
    "state": "Wisconsin",
    "source": "website",
    "status": "lost",
    "score": 66,
    "lead_value": 14304.75,
    "last_activity_at": "2025-04-19T15:03:17",
    "is_qualified": false
  },
  {
    "first_name": "Robert",
    "last_name": "Rivera",
    "email": "katherinesmith@adams.info",
    "phone": "1847143059286",
    "company": "Marsh LLC",
    "city": "Travisborough",
    "state": "Massachusetts",
    "source": "events",
    "status": "qualified",
    "score": 21,
    "lead_value": 43265.09,
    "last_activity_at": "2025-06-26T07:04:33",
    "is_qualified": true
  },
  {
    "first_name": "John",
    "last_name": "Lee",
    "email": "matthewkim@hotmail.com",
    "phone": "8806336482487",
    "company": "Roberts, Woodard and Williams",
    "city": "New Mikefurt",
    "state": "New Hampshire",
    "source": "facebook_ads",
    "status": "lost",
    "score": 23,
    "lead_value": 39503.1,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "John",
    "last_name": "Torres",
    "email": "walkersamantha@roberts-flores.biz",
    "phone": "7308520985133",
    "company": "Wilson, Montoya and Gutierrez",
    "city": "North Michelle",
    "state": "Arizona",
    "source": "website",
    "status": "contacted",
    "score": 0,
    "lead_value": 4181.52,
    "last_activity_at": "2025-06-12T04:37:32",
    "is_qualified": false
  },
  {
    "first_name": "Loretta",
    "last_name": "Graham",
    "email": "beverly93@rogers.com",
    "phone": "7590058944588",
    "company": "Bond, Watson and Lopez",
    "city": "Shaneburgh",
    "state": "South Dakota",
    "source": "google_ads",
    "status": "contacted",
    "score": 33,
    "lead_value": 46854.12,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Christopher",
    "last_name": "Prince",
    "email": "tchurch@bates.org",
    "phone": "9972139663248",
    "company": "Leon-Price",
    "city": "Port Ryan",
    "state": "West Virginia",
    "source": "website",
    "status": "won",
    "score": 80,
    "lead_value": 39418.54,
    "last_activity_at": "2025-07-03T04:40:40",
    "is_qualified": true
  },
  {
    "first_name": "Alexis",
    "last_name": "Kennedy",
    "email": "williamschristopher@hotmail.com",
    "phone": "2881521202353",
    "company": "Walker, Smith and Castro",
    "city": "New Bettyburgh",
    "state": "Louisiana",
    "source": "events",
    "status": "won",
    "score": 5,
    "lead_value": 6760.47,
    "last_activity_at": "2025-05-04T04:16:47",
    "is_qualified": true
  },
  {
    "first_name": "John",
    "last_name": "Guerrero",
    "email": "iburton@lopez.com",
    "phone": "8333262849413",
    "company": "Morales, Cruz and Ashley",
    "city": "East Christopherville",
    "state": "Arkansas",
    "source": "referral",
    "status": "won",
    "score": 22,
    "lead_value": 8816.28,
    "last_activity_at": "2025-06-24T02:15:59",
    "is_qualified": false
  },
  {
    "first_name": "Mary",
    "last_name": "Walls",
    "email": "tomgrant@combs-flores.org",
    "phone": "0778207051029",
    "company": "Campbell-Haley",
    "city": "Karenville",
    "state": "Kansas",
    "source": "facebook_ads",
    "status": "lost",
    "score": 40,
    "lead_value": 12418.02,
    "last_activity_at": "2025-07-22T17:23:30",
    "is_qualified": true
  },
  {
    "first_name": "Stephanie",
    "last_name": "Roberson",
    "email": "williamsmith@hotmail.com",
    "phone": "3086174565489",
    "company": "Lopez Group",
    "city": "Mckinneyview",
    "state": "Kansas",
    "source": "website",
    "status": "won",
    "score": 92,
    "lead_value": 1787.42,
    "last_activity_at": "2025-07-20T20:04:17",
    "is_qualified": false
  },
  {
    "first_name": "Charles",
    "last_name": "Barajas",
    "email": "rhondaespinoza@hotmail.com",
    "phone": "9020391397357",
    "company": "Le-Jackson",
    "city": "West Pamela",
    "state": "Alaska",
    "source": "google_ads",
    "status": "won",
    "score": 93,
    "lead_value": 20396.55,
    "last_activity_at": "2025-05-21T09:20:54",
    "is_qualified": false
  },
  {
    "first_name": "Jason",
    "last_name": "Schultz",
    "email": "joshua61@whitehead.com",
    "phone": "3705737323578",
    "company": "Ward Ltd",
    "city": "Farmerville",
    "state": "Wyoming",
    "source": "facebook_ads",
    "status": "won",
    "score": 63,
    "lead_value": 3664.17,
    "last_activity_at": "2025-02-28T14:43:08",
    "is_qualified": true
  },
  {
    "first_name": "Angela",
    "last_name": "Boone",
    "email": "marypayne@perez.biz",
    "phone": "8261722499906",
    "company": "Johnson-Russell",
    "city": "East Colinport",
    "state": "Illinois",
    "source": "other",
    "status": "contacted",
    "score": 38,
    "lead_value": 40713.88,
    "last_activity_at": "2025-06-24T23:46:23",
    "is_qualified": true
  },
  {
    "first_name": "Sara",
    "last_name": "Buchanan",
    "email": "nvalencia@branch-barber.com",
    "phone": "6000018665135",
    "company": "White Inc",
    "city": "Gutierrezchester",
    "state": "Arkansas",
    "source": "other",
    "status": "won",
    "score": 81,
    "lead_value": 31725.49,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Allison",
    "last_name": "Wang",
    "email": "xrobertson@gmail.com",
    "phone": "2187060599604",
    "company": "Stephens LLC",
    "city": "Mitchelltown",
    "state": "South Carolina",
    "source": "google_ads",
    "status": "contacted",
    "score": 100,
    "lead_value": 10198.5,
    "last_activity_at": "2025-03-05T20:26:30",
    "is_qualified": true
  },
  {
    "first_name": "Brandon",
    "last_name": "Williams",
    "email": "michael93@mueller.info",
    "phone": "8622123898045",
    "company": "Gonzalez, Thornton and Rush",
    "city": "Robertstad",
    "state": "Kansas",
    "source": "google_ads",
    "status": "won",
    "score": 54,
    "lead_value": 6642.87,
    "last_activity_at": "2025-07-01T23:19:13",
    "is_qualified": false
  },
  {
    "first_name": "Susan",
    "last_name": "Taylor",
    "email": "joseph24@gmail.com",
    "phone": "1776500331491",
    "company": "White and Sons",
    "city": "Pattersonview",
    "state": "Nebraska",
    "source": "other",
    "status": "won",
    "score": 98,
    "lead_value": 42919.49,
    "last_activity_at": "2025-02-24T02:55:06",
    "is_qualified": true
  },
  {
    "first_name": "Jose",
    "last_name": "Ochoa",
    "email": "holmesjuan@foster-short.com",
    "phone": "3968624400425",
    "company": "Rodriguez, Wood and Martinez",
    "city": "Gibsonchester",
    "state": "Idaho",
    "source": "website",
    "status": "contacted",
    "score": 17,
    "lead_value": 31903.55,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Jonathan",
    "last_name": "Snyder",
    "email": "xmaldonado@gmail.com",
    "phone": "2563465400355",
    "company": "Hendrix-Martinez",
    "city": "Anthonyhaven",
    "state": "Texas",
    "source": "other",
    "status": "contacted",
    "score": 89,
    "lead_value": 3247.38,
    "last_activity_at": "2025-08-10T01:33:09",
    "is_qualified": true
  },
  {
    "first_name": "Julie",
    "last_name": "Nelson",
    "email": "belljennifer@gmail.com",
    "phone": "8209345887541",
    "company": "Marks and Sons",
    "city": "Kimberlybury",
    "state": "Idaho",
    "source": "other",
    "status": "contacted",
    "score": 56,
    "lead_value": 26347.23,
    "last_activity_at": "2025-07-26T12:04:10",
    "is_qualified": false
  },
  {
    "first_name": "Molly",
    "last_name": "Perkins",
    "email": "evanscourtney@yahoo.com",
    "phone": "3320600460337",
    "company": "Hernandez Ltd",
    "city": "North Carlostown",
    "state": "Illinois",
    "source": "facebook_ads",
    "status": "new",
    "score": 16,
    "lead_value": 40544.03,
    "last_activity_at": "2025-03-02T04:54:00",
    "is_qualified": false
  },
  {
    "first_name": "Ashley",
    "last_name": "Miller",
    "email": "zpetersen@davis.com",
    "phone": "8746947089264",
    "company": "Wilson, Brown and Clark",
    "city": "Port Nicholas",
    "state": "Delaware",
    "source": "referral",
    "status": "won",
    "score": 33,
    "lead_value": 10575.07,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Jamie",
    "last_name": "Townsend",
    "email": "hornralph@gmail.com",
    "phone": "0681836856349",
    "company": "Holland, Ward and Hammond",
    "city": "Yatesview",
    "state": "Utah",
    "source": "website",
    "status": "new",
    "score": 55,
    "lead_value": 47780.23,
    "last_activity_at": "2025-03-06T15:11:11",
    "is_qualified": false
  },
  {
    "first_name": "Michaela",
    "last_name": "Marshall",
    "email": "michaelmann@adkins-gallagher.com",
    "phone": "8208915045832",
    "company": "Elliott-Davenport",
    "city": "Gonzaleztown",
    "state": "Indiana",
    "source": "google_ads",
    "status": "contacted",
    "score": 7,
    "lead_value": 21257.91,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "John",
    "last_name": "King",
    "email": "castrochristina@yahoo.com",
    "phone": "3398897583741",
    "company": "Krueger Group",
    "city": "Josephfurt",
    "state": "Kansas",
    "source": "website",
    "status": "contacted",
    "score": 42,
    "lead_value": 26438.22,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Tony",
    "last_name": "Coffey",
    "email": "kelseyfreeman@gmail.com",
    "phone": "7702147475447",
    "company": "Gutierrez PLC",
    "city": "Reyeshaven",
    "state": "Ohio",
    "source": "events",
    "status": "new",
    "score": 20,
    "lead_value": 30699.36,
    "last_activity_at": "2025-08-17T15:47:04",
    "is_qualified": true
  },
  {
    "first_name": "Chelsea",
    "last_name": "Davies",
    "email": "teresa44@gmail.com",
    "phone": "3625408936863",
    "company": "Miller-Roy",
    "city": "South Alexanderchester",
    "state": "Florida",
    "source": "website",
    "status": "contacted",
    "score": 4,
    "lead_value": 26172.34,
    "last_activity_at": "2025-07-12T22:13:48",
    "is_qualified": true
  },
  {
    "first_name": "Ronald",
    "last_name": "Beck",
    "email": "psmith@anderson.biz",
    "phone": "4537457818568",
    "company": "Thompson PLC",
    "city": "Port Charlesbury",
    "state": "Delaware",
    "source": "website",
    "status": "lost",
    "score": 77,
    "lead_value": 16565.28,
    "last_activity_at": "2025-03-14T04:12:13",
    "is_qualified": false
  },
  {
    "first_name": "Nicole",
    "last_name": "Rodgers",
    "email": "kweber@atkinson.info",
    "phone": "5078015970725",
    "company": "Byrd-Reyes",
    "city": "East Dawnborough",
    "state": "Michigan",
    "source": "referral",
    "status": "new",
    "score": 86,
    "lead_value": 37560.3,
    "last_activity_at": "2025-07-18T03:54:39",
    "is_qualified": false
  },
  {
    "first_name": "John",
    "last_name": "Smith",
    "email": "scott90@yahoo.com",
    "phone": "9134989767539",
    "company": "Schwartz-Anderson",
    "city": "Contreraschester",
    "state": "Maryland",
    "source": "referral",
    "status": "won",
    "score": 81,
    "lead_value": 20083.94,
    "last_activity_at": "2025-03-12T22:51:40",
    "is_qualified": false
  },
  {
    "first_name": "Ryan",
    "last_name": "Herman",
    "email": "olevy@yahoo.com",
    "phone": "2759104843720",
    "company": "Durham, Lynch and Garcia",
    "city": "Rachelville",
    "state": "Louisiana",
    "source": "referral",
    "status": "qualified",
    "score": 49,
    "lead_value": 45505.9,
    "last_activity_at": "2025-06-18T07:15:19",
    "is_qualified": true
  },
  {
    "first_name": "Jesse",
    "last_name": "Freeman",
    "email": "phall@harvey.com",
    "phone": "3617437566135",
    "company": "Stuart, Chavez and Reyes",
    "city": "South Andrew",
    "state": "Nevada",
    "source": "other",
    "status": "won",
    "score": 33,
    "lead_value": 15914.41,
    "last_activity_at": "2025-04-03T00:24:59",
    "is_qualified": false
  },
  {
    "first_name": "Charles",
    "last_name": "Hudson",
    "email": "stewartanna@yahoo.com",
    "phone": "5942971524790",
    "company": "Mckinney-Hicks",
    "city": "South Courtneyburgh",
    "state": "Arizona",
    "source": "facebook_ads",
    "status": "contacted",
    "score": 23,
    "lead_value": 23271.22,
    "last_activity_at": "2025-08-14T19:40:41",
    "is_qualified": false
  },
  {
    "first_name": "Alan",
    "last_name": "Baxter",
    "email": "joan39@yahoo.com",
    "phone": "4269117905053",
    "company": "Flores, Campos and Davis",
    "city": "Brandonberg",
    "state": "New Jersey",
    "source": "facebook_ads",
    "status": "contacted",
    "score": 95,
    "lead_value": 1732.86,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Michael",
    "last_name": "Greene",
    "email": "wlewis@gmail.com",
    "phone": "4814442805503",
    "company": "Mann, Smith and Watson",
    "city": "Joshuachester",
    "state": "New York",
    "source": "google_ads",
    "status": "won",
    "score": 86,
    "lead_value": 28769.6,
    "last_activity_at": "2025-07-25T16:58:21",
    "is_qualified": false
  },
  {
    "first_name": "Joseph",
    "last_name": "Washington",
    "email": "dakota17@fernandez.org",
    "phone": "9941634007696",
    "company": "Adams-Pierce",
    "city": "Garciaton",
    "state": "Vermont",
    "source": "facebook_ads",
    "status": "contacted",
    "score": 46,
    "lead_value": 27893.38,
    "last_activity_at": "2025-06-01T21:22:16",
    "is_qualified": false
  },
  {
    "first_name": "Angelica",
    "last_name": "Davis",
    "email": "ayersandrew@gmail.com",
    "phone": "1199558188420",
    "company": "Hall-Murillo",
    "city": "Port Pamelaborough",
    "state": "Rhode Island",
    "source": "other",
    "status": "won",
    "score": 55,
    "lead_value": 26693.96,
    "last_activity_at": "2025-07-17T12:29:06",
    "is_qualified": false
  },
  {
    "first_name": "Michelle",
    "last_name": "Robertson",
    "email": "jjohnson@day.com",
    "phone": "7308712800097",
    "company": "Wise-Villarreal",
    "city": "Port Cynthia",
    "state": "Virginia",
    "source": "website",
    "status": "lost",
    "score": 66,
    "lead_value": 2869.03,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Katherine",
    "last_name": "Fuentes",
    "email": "muellerjamie@mosley.net",
    "phone": "9832471459313",
    "company": "Simpson LLC",
    "city": "Hallside",
    "state": "Maine",
    "source": "referral",
    "status": "new",
    "score": 62,
    "lead_value": 26920.39,
    "last_activity_at": "2025-07-19T15:21:23",
    "is_qualified": false
  },
  {
    "first_name": "Rhonda",
    "last_name": "Thompson",
    "email": "ucarter@gmail.com",
    "phone": "3966799654420",
    "company": "Diaz, Stephens and Griffith",
    "city": "Fordtown",
    "state": "Oregon",
    "source": "facebook_ads",
    "status": "lost",
    "score": 65,
    "lead_value": 3373.1,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Christopher",
    "last_name": "Kline",
    "email": "anthonythomas@gonzales.com",
    "phone": "8828748862630",
    "company": "Watson-Rios",
    "city": "Ingramchester",
    "state": "Georgia",
    "source": "facebook_ads",
    "status": "lost",
    "score": 66,
    "lead_value": 47576.99,
    "last_activity_at": "2025-02-28T13:39:11",
    "is_qualified": false
  },
  {
    "first_name": "Sarah",
    "last_name": "Jones",
    "email": "bryan83@hotmail.com",
    "phone": "7342607699374",
    "company": "Hogan-Hicks",
    "city": "Jenniferview",
    "state": "Mississippi",
    "source": "google_ads",
    "status": "lost",
    "score": 46,
    "lead_value": 26454.44,
    "last_activity_at": "2025-03-11T22:36:05",
    "is_qualified": false
  },
  {
    "first_name": "Alicia",
    "last_name": "Williams",
    "email": "thompsonjohn@hess-drake.com",
    "phone": "6524459857341",
    "company": "Dillon-Jackson",
    "city": "Taylorview",
    "state": "Illinois",
    "source": "google_ads",
    "status": "new",
    "score": 77,
    "lead_value": 39324.84,
    "last_activity_at": "2025-05-27T13:32:38",
    "is_qualified": true
  },
  {
    "first_name": "Julia",
    "last_name": "Vaughan",
    "email": "rlowery@cameron.com",
    "phone": "6510251148269",
    "company": "Boyd-Hall",
    "city": "Chandlerfurt",
    "state": "Virginia",
    "source": "events",
    "status": "lost",
    "score": 2,
    "lead_value": 5570.43,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Aaron",
    "last_name": "Wilson",
    "email": "vgutierrez@yahoo.com",
    "phone": "2020575929630",
    "company": "Duncan, Hale and Herring",
    "city": "West Nicholastown",
    "state": "Hawaii",
    "source": "other",
    "status": "contacted",
    "score": 75,
    "lead_value": 31561.39,
    "last_activity_at": "2025-03-17T09:37:25",
    "is_qualified": false
  },
  {
    "first_name": "Marissa",
    "last_name": "Barrett",
    "email": "kaylee59@gmail.com",
    "phone": "8417302779335",
    "company": "Collins, Smith and Spencer",
    "city": "Barnettport",
    "state": "Kansas",
    "source": "google_ads",
    "status": "lost",
    "score": 85,
    "lead_value": 37197.71,
    "last_activity_at": "2025-03-24T01:16:01",
    "is_qualified": true
  },
  {
    "first_name": "Antonio",
    "last_name": "Jenkins",
    "email": "stacey11@friedman.net",
    "phone": "4239553406711",
    "company": "Kaiser LLC",
    "city": "Heidiberg",
    "state": "Iowa",
    "source": "website",
    "status": "lost",
    "score": 22,
    "lead_value": 5642.86,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Edward",
    "last_name": "Davis",
    "email": "emily36@gmail.com",
    "phone": "0986102680800",
    "company": "Williams, Murphy and Potter",
    "city": "Sandrabury",
    "state": "Virginia",
    "source": "referral",
    "status": "won",
    "score": 75,
    "lead_value": 37451.54,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Cole",
    "last_name": "Meyers",
    "email": "woodstephanie@adams.com",
    "phone": "3832539725036",
    "company": "Johnson Group",
    "city": "Steeleton",
    "state": "Texas",
    "source": "events",
    "status": "qualified",
    "score": 12,
    "lead_value": 24307.13,
    "last_activity_at": "2025-03-21T00:08:39",
    "is_qualified": true
  },
  {
    "first_name": "Heather",
    "last_name": "Cole",
    "email": "danielle37@ramirez.com",
    "phone": "5496302142868",
    "company": "Martin-Bailey",
    "city": "Jacquelinefort",
    "state": "Kansas",
    "source": "other",
    "status": "lost",
    "score": 8,
    "lead_value": 16486.32,
    "last_activity_at": "2025-03-27T16:10:34",
    "is_qualified": false
  },
  {
    "first_name": "George",
    "last_name": "Ford",
    "email": "ipierce@stevens-simmons.com",
    "phone": "2217773572123",
    "company": "Bryant LLC",
    "city": "Sanchezmouth",
    "state": "Kentucky",
    "source": "referral",
    "status": "contacted",
    "score": 42,
    "lead_value": 44665.48,
    "last_activity_at": "2025-08-08T23:40:25",
    "is_qualified": false
  },
  {
    "first_name": "Michael",
    "last_name": "Murphy",
    "email": "nicole00@dunn.com",
    "phone": "7899891015930",
    "company": "Figueroa PLC",
    "city": "Allenview",
    "state": "Georgia",
    "source": "referral",
    "status": "won",
    "score": 35,
    "lead_value": 37579.7,
    "last_activity_at": "2025-03-27T01:03:40",
    "is_qualified": true
  },
  {
    "first_name": "Roberto",
    "last_name": "Cole",
    "email": "collinsaaron@parker-spencer.biz",
    "phone": "4605320028191",
    "company": "Salas and Sons",
    "city": "Leeshire",
    "state": "New York",
    "source": "google_ads",
    "status": "new",
    "score": 62,
    "lead_value": 21746.47,
    "last_activity_at": "2025-07-21T03:48:15",
    "is_qualified": false
  },
  {
    "first_name": "Fred",
    "last_name": "Johnson",
    "email": "jeremy39@hotmail.com",
    "phone": "0584156859661",
    "company": "Moyer-Ross",
    "city": "Port Tylerfort",
    "state": "Hawaii",
    "source": "referral",
    "status": "new",
    "score": 20,
    "lead_value": 12857.08,
    "last_activity_at": "2025-04-21T10:46:59",
    "is_qualified": false
  },
  {
    "first_name": "Joseph",
    "last_name": "Hicks",
    "email": "veronica92@benson-chavez.com",
    "phone": "9792643775160",
    "company": "Davidson, West and Walsh",
    "city": "South Jeromestad",
    "state": "Nebraska",
    "source": "facebook_ads",
    "status": "new",
    "score": 62,
    "lead_value": 49773.19,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Shannon",
    "last_name": "Cooper",
    "email": "jbryant@hotmail.com",
    "phone": "7066802998027",
    "company": "Rose Group",
    "city": "Port Matthew",
    "state": "Connecticut",
    "source": "website",
    "status": "lost",
    "score": 59,
    "lead_value": 8877.57,
    "last_activity_at": "2025-08-01T18:58:06",
    "is_qualified": true
  },
  {
    "first_name": "Victoria",
    "last_name": "Lynch",
    "email": "mary93@yahoo.com",
    "phone": "7639497682016",
    "company": "Rivas, Johnson and Gonzalez",
    "city": "South Donnachester",
    "state": "New Hampshire",
    "source": "website",
    "status": "new",
    "score": 39,
    "lead_value": 49433.43,
    "last_activity_at": "2025-05-11T01:39:29",
    "is_qualified": false
  },
  {
    "first_name": "Aaron",
    "last_name": "Freeman",
    "email": "karina40@yahoo.com",
    "phone": "0561646122593",
    "company": "Smith LLC",
    "city": "Whitefurt",
    "state": "Missouri",
    "source": "referral",
    "status": "qualified",
    "score": 74,
    "lead_value": 47594.72,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Briana",
    "last_name": "Carter",
    "email": "lisa95@hotmail.com",
    "phone": "2421364020782",
    "company": "Kelley-Wallace",
    "city": "Port Johnfort",
    "state": "North Carolina",
    "source": "referral",
    "status": "new",
    "score": 78,
    "lead_value": 26808.27,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Judith",
    "last_name": "Daniels",
    "email": "kennethlong@hotmail.com",
    "phone": "9445933840448",
    "company": "Watson Ltd",
    "city": "South Matthewtown",
    "state": "Nebraska",
    "source": "events",
    "status": "new",
    "score": 18,
    "lead_value": 15734.76,
    "last_activity_at": "2025-05-21T01:34:30",
    "is_qualified": true
  },
  {
    "first_name": "Alyssa",
    "last_name": "Mann",
    "email": "amylawrence@gmail.com",
    "phone": "9774995269300",
    "company": "Vasquez-Perez",
    "city": "Lake Kathy",
    "state": "Hawaii",
    "source": "facebook_ads",
    "status": "qualified",
    "score": 6,
    "lead_value": 40023.12,
    "last_activity_at": "2025-07-05T19:31:15",
    "is_qualified": false
  },
  {
    "first_name": "Jill",
    "last_name": "Kelly",
    "email": "rebecca73@hotmail.com",
    "phone": "9466357595134",
    "company": "Phelps Ltd",
    "city": "East Marie",
    "state": "Virginia",
    "source": "facebook_ads",
    "status": "new",
    "score": 18,
    "lead_value": 29654.9,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Ashley",
    "last_name": "Wood",
    "email": "udavis@watson.com",
    "phone": "8677177349890",
    "company": "Moody, Meza and Higgins",
    "city": "Travisstad",
    "state": "Missouri",
    "source": "other",
    "status": "won",
    "score": 51,
    "lead_value": 6263.68,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Michael",
    "last_name": "Rivera",
    "email": "christophergalvan@yahoo.com",
    "phone": "8934644630708",
    "company": "Kelly, Jackson and Solis",
    "city": "Kaneview",
    "state": "Idaho",
    "source": "website",
    "status": "new",
    "score": 56,
    "lead_value": 37788.19,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Andrea",
    "last_name": "Smith",
    "email": "melissasellers@miller.net",
    "phone": "0159663581365",
    "company": "Hudson Ltd",
    "city": "Hubbardmouth",
    "state": "New Mexico",
    "source": "referral",
    "status": "lost",
    "score": 52,
    "lead_value": 39809.42,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Manuel",
    "last_name": "Williams",
    "email": "ashleycrawford@hunter.com",
    "phone": "1906373638085",
    "company": "Herrera PLC",
    "city": "Emmafurt",
    "state": "West Virginia",
    "source": "other",
    "status": "new",
    "score": 97,
    "lead_value": 30607.53,
    "last_activity_at": "2025-06-09T03:25:06",
    "is_qualified": true
  },
  {
    "first_name": "Tony",
    "last_name": "Diaz",
    "email": "jonathan80@anderson.com",
    "phone": "4368346387970",
    "company": "Bonilla PLC",
    "city": "Lake Ericstad",
    "state": "Mississippi",
    "source": "google_ads",
    "status": "won",
    "score": 57,
    "lead_value": 32325.55,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Kathleen",
    "last_name": "Smith",
    "email": "mcbridekatie@hotmail.com",
    "phone": "5580253399787",
    "company": "Obrien Inc",
    "city": "West Lauren",
    "state": "Ohio",
    "source": "google_ads",
    "status": "lost",
    "score": 5,
    "lead_value": 38387.84,
    "last_activity_at": "2025-04-04T16:48:59",
    "is_qualified": true
  },
  {
    "first_name": "Stacy",
    "last_name": "Jimenez",
    "email": "whitney08@smith.com",
    "phone": "9279437834551",
    "company": "Hernandez-Briggs",
    "city": "Fritzview",
    "state": "Florida",
    "source": "referral",
    "status": "lost",
    "score": 82,
    "lead_value": 19241.1,
    "last_activity_at": "2025-05-25T21:13:47",
    "is_qualified": false
  },
  {
    "first_name": "Kenneth",
    "last_name": "Ford",
    "email": "bellautumn@gmail.com",
    "phone": "5045586595499",
    "company": "Wilson Group",
    "city": "Princefort",
    "state": "Mississippi",
    "source": "events",
    "status": "contacted",
    "score": 32,
    "lead_value": 25293.51,
    "last_activity_at": "2025-06-02T21:45:31",
    "is_qualified": false
  },
  {
    "first_name": "Angela",
    "last_name": "Payne",
    "email": "jjohnson@sanders.com",
    "phone": "1978312427967",
    "company": "Lozano, Bell and Lewis",
    "city": "Howeland",
    "state": "Vermont",
    "source": "facebook_ads",
    "status": "won",
    "score": 12,
    "lead_value": 21975.51,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Tiffany",
    "last_name": "Hill",
    "email": "justin32@weber-perez.net",
    "phone": "8916091395395",
    "company": "Campbell-Finley",
    "city": "South James",
    "state": "New Mexico",
    "source": "referral",
    "status": "contacted",
    "score": 6,
    "lead_value": 16218.47,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Jason",
    "last_name": "Olson",
    "email": "hzamora@parker-silva.org",
    "phone": "9261383524389",
    "company": "Hernandez-Olson",
    "city": "Lake Michellestad",
    "state": "Nebraska",
    "source": "referral",
    "status": "contacted",
    "score": 35,
    "lead_value": 20837.03,
    "last_activity_at": "2025-06-13T23:17:31",
    "is_qualified": true
  },
  {
    "first_name": "Christine",
    "last_name": "Velasquez",
    "email": "eric48@williams-munoz.biz",
    "phone": "7145690575711",
    "company": "Benson-Hayden",
    "city": "Lake Kimberly",
    "state": "Oregon",
    "source": "facebook_ads",
    "status": "new",
    "score": 76,
    "lead_value": 13662.06,
    "last_activity_at": "2025-06-16T20:37:05",
    "is_qualified": false
  },
  {
    "first_name": "Laurie",
    "last_name": "Martinez",
    "email": "patrick64@fernandez-jones.info",
    "phone": "9694795991007",
    "company": "Vasquez-Donaldson",
    "city": "Laurenfurt",
    "state": "Washington",
    "source": "website",
    "status": "won",
    "score": 13,
    "lead_value": 23835.09,
    "last_activity_at": "2025-06-28T03:28:14",
    "is_qualified": true
  },
  {
    "first_name": "Justin",
    "last_name": "Fuller",
    "email": "saravelasquez@ward.net",
    "phone": "2082580933991",
    "company": "Roberts-Perez",
    "city": "Larryborough",
    "state": "New Mexico",
    "source": "google_ads",
    "status": "won",
    "score": 74,
    "lead_value": 48540.21,
    "last_activity_at": "2025-05-27T21:08:46",
    "is_qualified": false
  },
  {
    "first_name": "Meghan",
    "last_name": "Butler",
    "email": "jason99@gmail.com",
    "phone": "5399328312512",
    "company": "Lee, Ortiz and Cross",
    "city": "Lake Michaelside",
    "state": "New Mexico",
    "source": "other",
    "status": "contacted",
    "score": 5,
    "lead_value": 27514.99,
    "last_activity_at": "2025-03-13T10:33:48",
    "is_qualified": true
  },
  {
    "first_name": "John",
    "last_name": "Quinn",
    "email": "rogersjacqueline@castro-flores.com",
    "phone": "1071346288841",
    "company": "Robles Ltd",
    "city": "Port Michael",
    "state": "Vermont",
    "source": "website",
    "status": "new",
    "score": 66,
    "lead_value": 42938.68,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Tiffany",
    "last_name": "Chase",
    "email": "hernandezamanda@gmail.com",
    "phone": "0593266776509",
    "company": "Burton Ltd",
    "city": "Lake Heather",
    "state": "Utah",
    "source": "facebook_ads",
    "status": "qualified",
    "score": 53,
    "lead_value": 32534.61,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Teresa",
    "last_name": "Rose",
    "email": "benjamin06@hotmail.com",
    "phone": "8205665546096",
    "company": "Cross-Robbins",
    "city": "Marthafort",
    "state": "Arizona",
    "source": "website",
    "status": "lost",
    "score": 83,
    "lead_value": 35858.56,
    "last_activity_at": "2025-03-03T03:12:18",
    "is_qualified": true
  },
  {
    "first_name": "Nathan",
    "last_name": "Smith",
    "email": "isaiah34@jones.com",
    "phone": "4842509389397",
    "company": "Luna-Krause",
    "city": "Russellfurt",
    "state": "Oklahoma",
    "source": "events",
    "status": "won",
    "score": 31,
    "lead_value": 38088.52,
    "last_activity_at": "2025-03-01T07:28:55",
    "is_qualified": true
  },
  {
    "first_name": "Donna",
    "last_name": "Griffin",
    "email": "rodriguezkyle@hotmail.com",
    "phone": "8702252808386",
    "company": "Hunt, Johnson and Ellis",
    "city": "Port Emily",
    "state": "Michigan",
    "source": "google_ads",
    "status": "contacted",
    "score": 8,
    "lead_value": 7883.14,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Natalie",
    "last_name": "Lynch",
    "email": "rrodriguez@yahoo.com",
    "phone": "9065316670366",
    "company": "Marshall, Miller and Gomez",
    "city": "Susanton",
    "state": "North Dakota",
    "source": "events",
    "status": "lost",
    "score": 75,
    "lead_value": 7503.59,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Allison",
    "last_name": "Ray",
    "email": "davissandy@frazier.biz",
    "phone": "8262649091478",
    "company": "Jackson, Keller and Berry",
    "city": "Jonesburgh",
    "state": "Idaho",
    "source": "facebook_ads",
    "status": "qualified",
    "score": 32,
    "lead_value": 1794.69,
    "last_activity_at": "2025-04-18T08:50:08",
    "is_qualified": true
  },
  {
    "first_name": "Joshua",
    "last_name": "Ramirez",
    "email": "ashleygordon@adams.com",
    "phone": "4683664614086",
    "company": "Wu, Hogan and Mckinney",
    "city": "New Kiara",
    "state": "Delaware",
    "source": "google_ads",
    "status": "lost",
    "score": 7,
    "lead_value": 42839.87,
    "last_activity_at": "2025-04-28T18:45:07",
    "is_qualified": true
  },
  {
    "first_name": "Gabriel",
    "last_name": "Christian",
    "email": "lperry@yahoo.com",
    "phone": "0134186546656",
    "company": "Perez-Morse",
    "city": "Port Michelle",
    "state": "Oklahoma",
    "source": "referral",
    "status": "won",
    "score": 27,
    "lead_value": 42834.14,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Deanna",
    "last_name": "Duran",
    "email": "samantha87@hotmail.com",
    "phone": "9487756814205",
    "company": "Clark, Jones and Peters",
    "city": "South Tyler",
    "state": "Georgia",
    "source": "website",
    "status": "lost",
    "score": 58,
    "lead_value": 46592.7,
    "last_activity_at": "2025-07-25T13:38:52",
    "is_qualified": true
  },
  {
    "first_name": "Michaela",
    "last_name": "Lopez",
    "email": "zoe09@banks.biz",
    "phone": "1732807886227",
    "company": "Walsh LLC",
    "city": "West Alyssaburgh",
    "state": "Ohio",
    "source": "google_ads",
    "status": "new",
    "score": 71,
    "lead_value": 21224.78,
    "last_activity_at": "2025-07-26T14:44:19",
    "is_qualified": false
  },
  {
    "first_name": "Steven",
    "last_name": "Russo",
    "email": "victoriahoward@roberts-arias.net",
    "phone": "5226372810760",
    "company": "Forbes, Hartman and Taylor",
    "city": "Austinland",
    "state": "Arkansas",
    "source": "google_ads",
    "status": "lost",
    "score": 16,
    "lead_value": 36623.24,
    "last_activity_at": "2025-03-07T05:57:07",
    "is_qualified": false
  },
  {
    "first_name": "David",
    "last_name": "Lyons",
    "email": "tinaprice@yahoo.com",
    "phone": "4817499395034",
    "company": "Gonzalez Ltd",
    "city": "Kellyland",
    "state": "Kentucky",
    "source": "other",
    "status": "lost",
    "score": 69,
    "lead_value": 10509.58,
    "last_activity_at": "2025-02-26T06:55:35",
    "is_qualified": true
  },
  {
    "first_name": "Anthony",
    "last_name": "Price",
    "email": "jessicawolf@morton.com",
    "phone": "5245169554830",
    "company": "Lindsey Inc",
    "city": "Ellismouth",
    "state": "Pennsylvania",
    "source": "referral",
    "status": "won",
    "score": 43,
    "lead_value": 13837.8,
    "last_activity_at": "2025-03-07T09:52:09",
    "is_qualified": false
  },
  {
    "first_name": "Dawn",
    "last_name": "Moody",
    "email": "williamgreen@gmail.com",
    "phone": "5773894612429",
    "company": "Watkins PLC",
    "city": "Lake John",
    "state": "Massachusetts",
    "source": "other",
    "status": "lost",
    "score": 41,
    "lead_value": 16823.07,
    "last_activity_at": "2025-07-06T23:33:52",
    "is_qualified": false
  },
  {
    "first_name": "Elizabeth",
    "last_name": "Parker",
    "email": "zacharyclayton@gmail.com",
    "phone": "7211892742423",
    "company": "Jones-Bailey",
    "city": "Port Peggyville",
    "state": "Oregon",
    "source": "other",
    "status": "lost",
    "score": 5,
    "lead_value": 21278.55,
    "last_activity_at": "2025-05-01T16:12:19",
    "is_qualified": false
  },
  {
    "first_name": "Tina",
    "last_name": "Collins",
    "email": "michael75@gmail.com",
    "phone": "7739356013032",
    "company": "Fuentes-Baker",
    "city": "North Nicholas",
    "state": "Oregon",
    "source": "events",
    "status": "lost",
    "score": 73,
    "lead_value": 23737.59,
    "last_activity_at": "2025-07-02T07:48:31",
    "is_qualified": true
  },
  {
    "first_name": "Steven",
    "last_name": "Anderson",
    "email": "hburton@smith.info",
    "phone": "2387630955423",
    "company": "Anderson-Ryan",
    "city": "West Stephaniefort",
    "state": "Louisiana",
    "source": "facebook_ads",
    "status": "contacted",
    "score": 1,
    "lead_value": 15423.17,
    "last_activity_at": "2025-08-13T04:07:44",
    "is_qualified": false
  },
  {
    "first_name": "Alexander",
    "last_name": "Huffman",
    "email": "bobbyoneill@richards.com",
    "phone": "3571395016858",
    "company": "Roberson and Sons",
    "city": "Crystalberg",
    "state": "New Hampshire",
    "source": "google_ads",
    "status": "lost",
    "score": 6,
    "lead_value": 27757.68,
    "last_activity_at": "2025-02-25T10:11:55",
    "is_qualified": true
  },
  {
    "first_name": "Jacob",
    "last_name": "Clark",
    "email": "dawngolden@hotmail.com",
    "phone": "1503844948898",
    "company": "Wood Group",
    "city": "West Yvonne",
    "state": "Alabama",
    "source": "facebook_ads",
    "status": "contacted",
    "score": 98,
    "lead_value": 31092.71,
    "last_activity_at": "2025-04-01T05:11:32",
    "is_qualified": false
  },
  {
    "first_name": "Jessica",
    "last_name": "Nguyen",
    "email": "sue08@gmail.com",
    "phone": "0555416255354",
    "company": "Miller Group",
    "city": "Clarkemouth",
    "state": "California",
    "source": "website",
    "status": "lost",
    "score": 62,
    "lead_value": 46639.75,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Donna",
    "last_name": "Turner",
    "email": "matthewsfrancisco@hotmail.com",
    "phone": "1153148436300",
    "company": "Myers Inc",
    "city": "Toddmouth",
    "state": "Delaware",
    "source": "google_ads",
    "status": "qualified",
    "score": 36,
    "lead_value": 35212.62,
    "last_activity_at": "2025-03-16T17:43:35",
    "is_qualified": true
  },
  {
    "first_name": "Anita",
    "last_name": "Oneill",
    "email": "chavezsteven@yahoo.com",
    "phone": "2137204122085",
    "company": "Gutierrez-Fisher",
    "city": "Pittsport",
    "state": "Alabama",
    "source": "facebook_ads",
    "status": "contacted",
    "score": 16,
    "lead_value": 38162.01,
    "last_activity_at": "2025-05-24T07:22:51",
    "is_qualified": false
  },
  {
    "first_name": "Joyce",
    "last_name": "Bean",
    "email": "bvelazquez@harrison.com",
    "phone": "9666049303258",
    "company": "Castro-Bates",
    "city": "Williamsshire",
    "state": "Nebraska",
    "source": "facebook_ads",
    "status": "lost",
    "score": 77,
    "lead_value": 38829.24,
    "last_activity_at": "2025-03-01T21:49:33",
    "is_qualified": false
  },
  {
    "first_name": "Chad",
    "last_name": "Hill",
    "email": "angel64@hall.com",
    "phone": "7043205478606",
    "company": "Little Group",
    "city": "Port Raymondmouth",
    "state": "Nebraska",
    "source": "website",
    "status": "lost",
    "score": 9,
    "lead_value": 7139.43,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Amber",
    "last_name": "Parker",
    "email": "rachelbrooks@hotmail.com",
    "phone": "5848223552485",
    "company": "Phillips, Thompson and Price",
    "city": "Gonzalesside",
    "state": "Montana",
    "source": "google_ads",
    "status": "new",
    "score": 76,
    "lead_value": 31504.3,
    "last_activity_at": "2025-07-13T22:11:34",
    "is_qualified": false
  },
  {
    "first_name": "Lori",
    "last_name": "Davis",
    "email": "clawrence@hotmail.com",
    "phone": "3675564848778",
    "company": "Grant-Wright",
    "city": "West Amandaton",
    "state": "Washington",
    "source": "events",
    "status": "lost",
    "score": 53,
    "lead_value": 45588.41,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Maria",
    "last_name": "Richardson",
    "email": "wilsonkeith@gmail.com",
    "phone": "5869279599427",
    "company": "Johnson, Willis and Washington",
    "city": "Alyssashire",
    "state": "Georgia",
    "source": "events",
    "status": "contacted",
    "score": 78,
    "lead_value": 44312.78,
    "last_activity_at": "2025-04-04T02:42:03",
    "is_qualified": true
  },
  {
    "first_name": "Julie",
    "last_name": "Kent",
    "email": "christophermiller@hardy-payne.com",
    "phone": "6233725555796",
    "company": "Gonzalez, Harris and Cox",
    "city": "North Jacobbury",
    "state": "Utah",
    "source": "google_ads",
    "status": "contacted",
    "score": 17,
    "lead_value": 5506.8,
    "last_activity_at": "2025-07-12T23:36:49",
    "is_qualified": false
  },
  {
    "first_name": "Gregory",
    "last_name": "Turner",
    "email": "jason95@gmail.com",
    "phone": "7686650483579",
    "company": "Ferguson-Miller",
    "city": "Reillyville",
    "state": "Kansas",
    "source": "events",
    "status": "contacted",
    "score": 6,
    "lead_value": 46133.4,
    "last_activity_at": "2025-04-21T19:54:32",
    "is_qualified": true
  },
  {
    "first_name": "Jorge",
    "last_name": "Mullen",
    "email": "glenda39@ortega.info",
    "phone": "0072358088269",
    "company": "Armstrong, Hughes and Green",
    "city": "South Jeanettestad",
    "state": "Kentucky",
    "source": "events",
    "status": "new",
    "score": 35,
    "lead_value": 26129.02,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Michael",
    "last_name": "Watson",
    "email": "sarah23@bailey.com",
    "phone": "2480994121003",
    "company": "Hill-Phelps",
    "city": "West Michael",
    "state": "Louisiana",
    "source": "google_ads",
    "status": "won",
    "score": 92,
    "lead_value": 39132.98,
    "last_activity_at": "2025-08-22T20:35:15",
    "is_qualified": false
  },
  {
    "first_name": "Cody",
    "last_name": "Martin",
    "email": "whitneyalexis@duffy.net",
    "phone": "4757904556218",
    "company": "Phillips Group",
    "city": "Luceroport",
    "state": "California",
    "source": "referral",
    "status": "won",
    "score": 100,
    "lead_value": 45300.59,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Ashley",
    "last_name": "Young",
    "email": "uthomas@hotmail.com",
    "phone": "7132327668901",
    "company": "Gonzales-Garrett",
    "city": "Marilynmouth",
    "state": "New Jersey",
    "source": "referral",
    "status": "contacted",
    "score": 96,
    "lead_value": 9483.52,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Adam",
    "last_name": "Christensen",
    "email": "nicholspatrick@gmail.com",
    "phone": "3055521159339",
    "company": "Reed-Fuentes",
    "city": "Jenniferport",
    "state": "Florida",
    "source": "website",
    "status": "lost",
    "score": 13,
    "lead_value": 12279.78,
    "last_activity_at": "2025-08-04T17:35:51",
    "is_qualified": false
  },
  {
    "first_name": "Andrew",
    "last_name": "Lopez",
    "email": "kingalicia@hotmail.com",
    "phone": "1826460021866",
    "company": "Fisher-Barker",
    "city": "Bonillamouth",
    "state": "Montana",
    "source": "facebook_ads",
    "status": "lost",
    "score": 89,
    "lead_value": 46476.67,
    "last_activity_at": "2025-03-16T12:20:11",
    "is_qualified": true
  },
  {
    "first_name": "Tracy",
    "last_name": "Campos",
    "email": "mariacompton@richardson-johnson.com",
    "phone": "6608039175431",
    "company": "Wu-Yang",
    "city": "South Madisonport",
    "state": "South Dakota",
    "source": "facebook_ads",
    "status": "new",
    "score": 59,
    "lead_value": 19688.01,
    "last_activity_at": "2025-08-19T03:33:14",
    "is_qualified": false
  },
  {
    "first_name": "Dawn",
    "last_name": "Garrison",
    "email": "wwright@thomas.com",
    "phone": "7268511962651",
    "company": "Richardson and Sons",
    "city": "West Williamchester",
    "state": "Oregon",
    "source": "google_ads",
    "status": "lost",
    "score": 49,
    "lead_value": 19637.43,
    "last_activity_at": "2025-06-13T22:38:15",
    "is_qualified": true
  },
  {
    "first_name": "Rodney",
    "last_name": "Gates",
    "email": "grace83@williams-compton.com",
    "phone": "4452928707249",
    "company": "Hall, Torres and Jacobs",
    "city": "Rayland",
    "state": "Connecticut",
    "source": "google_ads",
    "status": "contacted",
    "score": 66,
    "lead_value": 33565.71,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Kevin",
    "last_name": "Robertson",
    "email": "josephgolden@hotmail.com",
    "phone": "1695138405131",
    "company": "Adams, Griffith and Cuevas",
    "city": "Allenhaven",
    "state": "New Hampshire",
    "source": "facebook_ads",
    "status": "won",
    "score": 38,
    "lead_value": 42951.86,
    "last_activity_at": "2025-06-22T13:38:49",
    "is_qualified": true
  },
  {
    "first_name": "Benjamin",
    "last_name": "Blevins",
    "email": "mperkins@gmail.com",
    "phone": "0612394896930",
    "company": "Roberts and Sons",
    "city": "North Patricia",
    "state": "New Jersey",
    "source": "facebook_ads",
    "status": "won",
    "score": 1,
    "lead_value": 29540.9,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Alexis",
    "last_name": "Goodwin",
    "email": "pricecassidy@gmail.com",
    "phone": "6954363607086",
    "company": "Thompson Inc",
    "city": "Hooverton",
    "state": "Arizona",
    "source": "referral",
    "status": "new",
    "score": 83,
    "lead_value": 6464.39,
    "last_activity_at": null,
    "is_qualified": true
  },
  {
    "first_name": "Kimberly",
    "last_name": "Foster",
    "email": "michael64@cortez.com",
    "phone": "9238005550209",
    "company": "Morales Inc",
    "city": "Deniseton",
    "state": "Idaho",
    "source": "facebook_ads",
    "status": "qualified",
    "score": 49,
    "lead_value": 2307.57,
    "last_activity_at": "2025-04-21T04:31:34",
    "is_qualified": false
  },
  {
    "first_name": "Emily",
    "last_name": "Johnson",
    "email": "lukerussell@thomas-johnson.biz",
    "phone": "2949439736502",
    "company": "Watson and Sons",
    "city": "New Melissa",
    "state": "Kansas",
    "source": "website",
    "status": "lost",
    "score": 41,
    "lead_value": 18542.32,
    "last_activity_at": "2025-03-08T16:00:43",
    "is_qualified": true
  },
  {
    "first_name": "James",
    "last_name": "Williams",
    "email": "anthonyryan@gmail.com",
    "phone": "9964087955251",
    "company": "Smith PLC",
    "city": "Port Louisfurt",
    "state": "South Dakota",
    "source": "events",
    "status": "qualified",
    "score": 92,
    "lead_value": 11128.6,
    "last_activity_at": "2025-05-29T14:42:53",
    "is_qualified": false
  },
  {
    "first_name": "Joseph",
    "last_name": "Nash",
    "email": "lawrence86@yahoo.com",
    "phone": "7103238631579",
    "company": "Gomez PLC",
    "city": "Millerside",
    "state": "Alaska",
    "source": "facebook_ads",
    "status": "lost",
    "score": 53,
    "lead_value": 48800.37,
    "last_activity_at": "2025-02-26T18:29:59",
    "is_qualified": false
  },
  {
    "first_name": "Crystal",
    "last_name": "Martin",
    "email": "caleb67@nelson-robertson.net",
    "phone": "6144198815291",
    "company": "Braun LLC",
    "city": "East Jessica",
    "state": "Connecticut",
    "source": "google_ads",
    "status": "contacted",
    "score": 30,
    "lead_value": 4430.29,
    "last_activity_at": null,
    "is_qualified": false
  },
  {
    "first_name": "Cathy",
    "last_name": "Jones",
    "email": "manningvalerie@hotmail.com",
    "phone": "9505512893852",
    "company": "Beck, Schneider and Alexander",
    "city": "Robertborough",
    "state": "Mississippi",
    "source": "other",
    "status": "contacted",
    "score": 65,
    "lead_value": 47171.7,
    "last_activity_at": "2025-03-27T16:31:07",
    "is_qualified": true
  },
  {
    "first_name": "Dustin",
    "last_name": "Thomas",
    "email": "bensonkimberly@gmail.com",
    "phone": "4957207970357",
    "company": "Wilson-Lewis",
    "city": "North Krista",
    "state": "Wyoming",
    "source": "events",
    "status": "new",
    "score": 92,
    "lead_value": 30405.59,
    "last_activity_at": "2025-03-11T18:24:33",
    "is_qualified": false
  },
  {
    "first_name": "Anthony",
    "last_name": "Cook",
    "email": "allengregory@yahoo.com",
    "phone": "7483896619685",
    "company": "Rosales, Flores and Barber",
    "city": "Mcdonaldmouth",
    "state": "California",
    "source": "events",
    "status": "contacted",
    "score": 5,
    "lead_value": 13288.39,
    "last_activity_at": "2025-06-25T16:35:17",
    "is_qualified": false
  },
  {
    "first_name": "Andrew",
    "last_name": "Thomas",
    "email": "richardsanchez@hotmail.com",
    "phone": "3003695865555",
    "company": "Walsh PLC",
    "city": "Kristinberg",
    "state": "Louisiana",
    "source": "events",
    "status": "won",
    "score": 2,
    "lead_value": 49926.41,
    "last_activity_at": "2025-07-31T16:55:13",
    "is_qualified": false
  },
  {
    "first_name": "Rhonda",
    "last_name": "Greene",
    "email": "jessicanunez@gomez-sims.com",
    "phone": "1337046319608",
    "company": "Day PLC",
    "city": "Jenkinsborough",
    "state": "Idaho",
    "source": "other",
    "status": "won",
    "score": 32,
    "lead_value": 17720.56,
    "last_activity_at": "2025-07-30T22:46:27",
    "is_qualified": true
  },
  {
    "first_name": "Devin",
    "last_name": "Stein",
    "email": "sheila11@mckenzie.com",
    "phone": "0056673149030",
    "company": "Lee, Chandler and Lewis",
    "city": "Colleenberg",
    "state": "Tennessee",
    "source": "website",
    "status": "won",
    "score": 34,
    "lead_value": 9113.0,
    "last_activity_at": "2025-08-22T10:54:55",
    "is_qualified": false
  },
  {
    "first_name": "Rebecca",
    "last_name": "Riley",
    "email": "gary56@hotmail.com",
    "phone": "7545514887846",
    "company": "Silva Ltd",
    "city": "South Elizabethmouth",
    "state": "Oregon",
    "source": "events",
    "status": "qualified",
    "score": 5,
    "lead_value": 25330.56,
    "last_activity_at": "2025-03-03T11:45:56",
    "is_qualified": false
  },
  {
    "first_name": "Amy",
    "last_name": "Mclean",
    "email": "ramseyjulie@edwards.com",
    "phone": "6403871147805",
    "company": "Clark, Shepard and Montgomery",
    "city": "Nicholasport",
    "state": "Kentucky",
    "source": "google_ads",
    "status": "contacted",
    "score": 11,
    "lead_value": 37256.91,
    "last_activity_at": "2025-05-07T11:32:06",
    "is_qualified": false
  },
  {
    "first_name": "Lori",
    "last_name": "Miller",
    "email": "markglover@gmail.com",
    "phone": "1974621668029",
    "company": "Fitzpatrick, Evans and Turner",
    "city": "Lake Regina",
    "state": "Montana",
    "source": "facebook_ads",
    "status": "qualified",
    "score": 13,
    "lead_value": 33391.21,
    "last_activity_at": "2025-07-12T12:31:49",
    "is_qualified": false
  }
]

export default {data:smapleLead};